package jav.gui.options;

import jav.gui.main.JTextFieldLimit;
import jav.gui.main.MainController;
import jav.logging.log4j.Log;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.util.NbPreferences;

/**
 *Copyright (c) 2012, IMPACT working group at the Centrum für Informations- und Sprachverarbeitung, University of Munich.
 *All rights reserved.

 *Redistribution and use in source and binary forms, with or without
 *modification, are permitted provided that the following conditions are met:

 *Redistributions of source code must retain the above copyright
 *notice, this list of conditions and the following disclaimer.
 *Redistributions in binary form must reproduce the above copyright
 *notice, this list of conditions and the following disclaimer in the
 *documentation and/or other materials provided with the distribution.

 *THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 *IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 *TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 *PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * This file is part of the ocr-postcorrection tool developed
 * by the IMPACT working group at the Centrum für Informations- und Sprachverarbeitung, University of Munich.
 * For further information and contacts visit http://ocr.cis.uni-muenchen.de/
 * 
 * @author thorsten (thorsten.vobl@googlemail.com)
 */
final class UserIDPanel extends javax.swing.JPanel implements DocumentListener {

    private final UserIDOptionsPanelController controller;

    UserIDPanel(UserIDOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        userId.setDocument(new JTextFieldLimit(36));
        userId.getDocument().addDocumentListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userId = new javax.swing.JTextField();
        profilerUrl = new javax.swing.JTextField();

        userId.setColumns(30);
        userId.setText(org.openide.util.NbBundle.getMessage(UserIDPanel.class, "UserIDPanel.userId.text")); // NOI18N
        userId.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(UserIDPanel.class, "UserIDPanel.userId.border.title"))); // NOI18N

        profilerUrl.setColumns(30);
        profilerUrl.setText(org.openide.util.NbBundle.getMessage(UserIDPanel.class, "UserIDPanel.profilerUrl.text")); // NOI18N
        profilerUrl.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(UserIDPanel.class, "UserIDPanel.profilerUrl.border.title"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userId, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(profilerUrl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(profilerUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        profilerUrl.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(UserIDPanel.class, "UserIDPanel.profilerUrl.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        userId.setText(NbPreferences.forModule(MainController.class).get("profiler_user_id", ""));
        profilerUrl.setText(NbPreferences.forModule(MainController.class).get("profiler_service_url", ""));
        Log.debug(this, "load() profiler_user_id: '%s'", userId.getText());
        Log.debug(this, "load() profiler_service_url: '%s'", profilerUrl.getText());
    }

    void store() {
        Log.debug(this, "store() profiler_user_id: '%s'", userId.getText());
        Log.debug(this, "store() profiler_service_url: '%s'", userId.getText());
        NbPreferences.forModule(MainController.class).put("profiler_user_id", userId.getText());
        NbPreferences.forModule(MainController.class).put("profiler_service_url", profilerUrl.getText());
    }

    boolean valid() {
        return userIdIsValid() && profilerUrlIsValid();
    }
    private boolean userIdIsValid() {
        return userId.getText().equals("") || 
            userId.getText().matches(".{8}-.{4}-.{4}-.{4}-.{12}");
    }
    private boolean profilerUrlIsValid() {
        return profilerUrl.getText().equals("") ||
            profilerUrl.getText().matches("https?://.*");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField profilerUrl;
    private javax.swing.JTextField userId;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertUpdate(DocumentEvent e) {
        controller.changed();
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        controller.changed();
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        controller.changed();
    }
}